"use strict";function _slicedToArray(arr,i){return _arrayWithHoles(arr)||_iterableToArrayLimit(arr,i)||_unsupportedIterableToArray(arr,i)||_nonIterableRest()}function _nonIterableRest(){throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}function _unsupportedIterableToArray(o,minLen){if(!o)return;if(typeof o==="string")return _arrayLikeToArray(o,minLen);var n=Object.prototype.toString.call(o).slice(8,-1);if(n==="Object"&&o.constructor)n=o.constructor.name;if(n==="Map"||n==="Set")return Array.from(o);if(n==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return _arrayLikeToArray(o,minLen)}function _arrayLikeToArray(arr,len){if(len==null||len>arr.length)len=arr.length;for(var i=0,arr2=new Array(len);i<len;i++)arr2[i]=arr[i];return arr2}function _iterableToArrayLimit(r,l){var t=null==r?null:"undefined"!=typeof Symbol&&r[Symbol.iterator]||r["@@iterator"];if(null!=t){var e,n,i,u,a=[],f=!0,o=!1;try{if(i=(t=t.call(r)).next,0===l){if(Object(t)!==t)return;f=!1}else for(;!(f=(e=i.call(t)).done)&&(a.push(e.value),a.length!==l);f=!0);}catch(r){o=!0,n=r}finally{try{if(!f&&null!=t.return&&(u=t.return(),Object(u)!==u))return}finally{if(o)throw n}}return a}}function _arrayWithHoles(arr){if(Array.isArray(arr))return arr}(function(){var audienceData=JSON.parse(document.getElementById("audience-data").dataset.audience);var dropdown=document.getElementById("countries-dropdown");var defaultCountry="Global";//set Global as default.
document.addEventListener("DOMContentLoaded",function(){initAudience()});dropdown.addEventListener("change",function(){updateHash(dropdown.value);updateValues(dropdown.value,audienceData)});function initAudience(){updateMauDau();populateCountriesDropdown(audienceData);// since the spreadsheet header row starts with the date, and then an empty column name ("June 2022,,..."), we need to remove the first two columns -slice(2)-, so it only matches the actual countries. The replace calls make sure the URL hash is converted to the same format the data is in the CSV. E.g. the URL hash could look like "South-Africa", and the CSV data shows "South Africa"
var selectedCountry=audienceData[0].slice(2).includes(location.hash.replace("#","").replace("_","/").replace("-"," "))?location.hash.replace("#",""):defaultCountry;if(selectedCountry!==defaultCountry){dropdown.options[getIndexFromCountryName(selectedCountry,dropdown)].selected=true}else{updateHash(selectedCountry)}updateValues(selectedCountry,audienceData)}function updateHash(selectedCountry){if(selectedCountry==defaultCountry){history.replaceState(null,null," ");//remove #Global from hash
}else{location.hash="#"+selectedCountry;// update hash
}}function updateMauDau(){/** TODO: this function should be merged with the one at js/transparency.js at some point. **/fetch("/transparency-data.json").then(function(data){return data.json()}).then(function(json){var latestData=Object.entries(json.users).reduce(function(accumulator,_ref){var _ref2=_slicedToArray(_ref,2),date=_ref2[0],data=_ref2[1];var mau=data.mau;var dau=data.dau;if(date>accumulator.dateString){accumulator.mau=mau/1e6;accumulator.dau=dau/1e6;accumulator.dateString=date}return accumulator},{dateString:"",mau:0,dau:0});var _latestData$dateStrin=latestData.dateString.split("-"),_latestData$dateStrin2=_slicedToArray(_latestData$dateStrin,2),year=_latestData$dateStrin2[0],month=_latestData$dateStrin2[1];var monthName=new Intl.DateTimeFormat("en",{month:"long",timeZone:"UTC"}).format(new Date(month));document.getElementById("mau").textContent=latestData.mau;document.getElementById("dau").textContent=latestData.dau;document.getElementById("survey-date").textContent=monthName+" "+year})}function populateCountriesDropdown(audienceData){audienceData[0].forEach(function(country,index){if(country.length&&index>0){var option=document.createElement("option");// Special characters in the URI are replaced for readability after encoding. For example, a country named "AU/NZ" in the CSV data would be encoded as "AU%2FNZ". After replacing the special character, it becomes "AU_NZ".
option.value=encodeURIComponent(country).replace("%20","-").replace("%2F","_");option.textContent=country;dropdown.appendChild(option)}})}/**
   * Creates an object with the results to every category from the CSV, 
   * then invokes the App function
   */function updateValues(countryName,audienceData){// To ensure URL readability, we may need to remove special separator characters from the countryName field. For example, "South-Africa" would be converted to "South Africa". However, the dash/underscore format will still be used for URL display and dropdown option values.
countryName=countryName.replace("_","/").replace("-"," ");var countryId=audienceData[0].indexOf(countryName);var obj={};obj["surveyDate"]=audienceData[0][0];obj["sampleSize"]=audienceData[1][countryId];var career={};for(var i=2;i<=10;i++){// from row 2 to 10 covers all answer options from career status
career[audienceData[i][1]]=parseFloat(audienceData[i][countryId].replace("%",""))}obj["career"]=career;var income={};for(var _i=14;_i<=20;_i++){// from row 14 to 20
income[audienceData[_i][1]]=parseFloat(audienceData[_i][countryId].replace("%",""))}obj["income"]=income;obj["gender"]={"male":roundPercent(audienceData[11][countryId]),"female":roundPercent(audienceData[12][countryId]),"other":roundPercent(audienceData[13][countryId])};obj["relationship"]={"single":roundPercent(audienceData[40][countryId]),"relationship":roundPercent(audienceData[41][countryId]),"other":roundPercent(audienceData[42][countryId])};obj["household"]={"pets":roundPercent(audienceData[28][countryId]),"kids":roundPercent(audienceData[29][countryId]),"vehicle":roundPercent(audienceData[30][countryId]),"purchaser":roundPercent(audienceData[31][countryId])};obj["adBlockingHabits"]={"users":parseInt(audienceData[32][countryId].replace("%",""))/10,"brave":roundPercent(audienceData[33][countryId])};obj["hobbies"]=[];for(var _i2=34;_i2<=39;_i2++){// from row 34 to 39
obj["hobbies"].push(roundPercent(audienceData[_i2][countryId]))}var averageAge={};for(var _i3=21;_i3<=27;_i3++){// from row 21 to 27
averageAge[audienceData[_i3][1]]=parseInt(audienceData[_i3][countryId].replace("%",""))}obj["averageAge"]=averageAge;App.renderData(obj)}/**
   * Populates each html element with the specific information it needs
   */var App={renderData:function renderData(data){this.renderCareerStatus(data.career);this.renderGender(data.gender);this.renderRelationship(data.relationship);this.renderIncomeBracket(data.income);this.renderAverageAge(data.averageAge);this.renderHousehold(data.household);this.renderAdBlockingHabits(data.adBlockingHabits);this.renderHobbiesAndInterests(data.hobbies);this.renderSampleSize(data.sampleSize);this.renderSurveyDate(data.surveyDate)},renderCareerStatus:function renderCareerStatus(data){var colors=["#E83D25","#3D469D","#7378B9","#AEB1C2","#F37657","#E83D25","#3D469D","#7378B9","#AEB1C2"];createChart("career-status",data,colors)},renderGender:function renderGender(genderData){var chart=document.getElementById("gender-chart");var maleNumber=parseInt(genderData.male.replace("%",""));chart.style.backgroundImage="linear-gradient(90deg, #3D469D "+maleNumber+"%, #FF4724 "+(maleNumber+13)+"%)";document.getElementById("gender-male").textContent=genderData.male;document.getElementById("gender-female").textContent=genderData.female;document.getElementById("gender-other").textContent=genderData.other},renderRelationship:function renderRelationship(relationshipData){var chart=document.getElementById("relationship-chart");var singleNumber=parseInt(relationshipData.single.replace("%",""));chart.style.backgroundImage="linear-gradient(90deg, #3D469D "+singleNumber+"%, #FF4724 "+(singleNumber+13)+"%)";document.getElementById("relationship-single").textContent=relationshipData.single;document.getElementById("relationship-relationship").textContent=relationshipData.relationship;document.getElementById("relationship-other").textContent=relationshipData.other},renderIncomeBracket:function renderIncomeBracket(data){var colors=["#2D3A7F","#525EAA","#7A86C2","#B3BDE0","#2D3A7F","#525EAA","#7A86C2"];createChart("income-bracket",data,colors,"pie")},renderAverageAge:function renderAverageAge(ageData){var averageAgeChart=document.querySelector("#average-age-chart ul");averageAgeChart.textContent="";Object.keys(ageData).forEach(function(key){var ageRow=document.createElement("li");ageRow.setAttribute("data-value",ageData[key]+"%");ageRow.style.setProperty("--dynamic-width",ageData[key]*1.8+"%");var span=document.createElement("span");span.classList.add("text");span.textContent=key;ageRow.appendChild(span);averageAgeChart.appendChild(ageRow)})},renderHousehold:function renderHousehold(householdData){document.getElementById("pets-at-home").textContent=householdData.pets;document.getElementById("kids-at-home").textContent=householdData.kids;document.getElementById("own-a-vehicle").textContent=householdData.vehicle;document.getElementById("primary-purchaser").textContent=householdData.purchaser},renderAdBlockingHabits:function renderAdBlockingHabits(habitsData){var personIcons=document.querySelectorAll("#ad-blocking-users-chart svg");var count=Math.round(habitsData.users);personIcons.forEach(function(personIcon){// iterates the 10 icons
if(count>0){personIcon.classList.add("active");// adds the active class to the first X (count) icons.
count--}else{personIcon.classList.remove("active");// removes the active class on refresh
}});document.getElementById("ad-blocking-users").textContent=habitsData.users;document.getElementById("ad-blocking-brave").textContent=habitsData.brave},renderHobbiesAndInterests:function renderHobbiesAndInterests(hobbies){document.getElementById("say-they-owntrade-cryptocurrency").textContent=hobbies[0];document.getElementById("say-movietv-is-a-top-interest").textContent=hobbies[1];document.getElementById("say-that-tech-is-a-top-interest").textContent=hobbies[2];document.getElementById("consider-themselves-gamers").textContent=hobbies[3];document.getElementById("say-that-music-is-a-top-interest").textContent=hobbies[4];document.getElementById("travel-more-than-twice-a-year").textContent=hobbies[5]},renderSampleSize:function renderSampleSize(sampleSize){document.getElementById("sample-size").textContent=sampleSize},renderSurveyDate:function renderSurveyDate(surveyDate){document.getElementById("survey-date-footer").textContent=surveyDate}};function createChart(itemId,data,colors){var type=arguments.length>3&&arguments[3]!==undefined?arguments[3]:"donut";// sorts percentages decreasingly.
var sortedData=[];for(var channel in data){sortedData.push([channel,data[channel]])}sortedData.sort(function(b,a){return a[1]-b[1]});// prepares data in an array of objects, each one contains label, color and count.
var preparedDataArray=[];sortedData.forEach(function(item,index){preparedDataArray.push({color:colors[index],label:item[0],value:item[1]})});//reset chart container
var chart=document.getElementById(itemId+"-chart");chart.textContent="";//reset legend
document.getElementById(itemId+"-legend").textContent="";// create chart
var svg=document.createElementNS("http://www.w3.org/2000/svg","svg");var filled=0;svg.setAttribute("width","100%");svg.setAttribute("height","100%");svg.setAttribute("viewBox","0 0 30 95");svg.classList.add(type);chart.appendChild(svg);preparedDataArray.forEach(function(chartItem){var circle=document.createElementNS("http://www.w3.org/2000/svg","circle");// donut (default)
var startAngle=-90,radius=25,cx=15,cy=45,strokeWidth=15,dashArray=2*Math.PI*radius,dashOffset=dashArray-dashArray*chartItem.value/100,angle=filled*360/100+startAngle;// pie
if(type=="pie"){startAngle=-90,radius=15.97,cx=15,cy=45,strokeWidth=32,dashArray=chartItem.value+.1+" 100",dashOffset=dashArray-dashArray*chartItem.value/100,angle=filled*360/100+startAngle}circle.setAttribute("r",radius);circle.setAttribute("cx",cx);circle.setAttribute("cy",cy);circle.setAttribute("fill","transparent");circle.setAttribute("stroke",chartItem.color);circle.dataset.channel=itemId+chartItem.label.toLowerCase();circle.setAttribute("stroke-width",strokeWidth);circle.setAttribute("stroke-dasharray",dashArray);circle.setAttribute("stroke-dashoffset",dashOffset);circle.setAttribute("transform","rotate("+angle+" "+cx+" "+cy+")");var radians=((filled+(filled+chartItem.value))/2*360/100+startAngle)*Math.PI/180;var textX=Math.cos(radians)*radius;var textY=Math.sin(radians)*radius;svg.appendChild(circle);// legend builder
var li=document.createElement("li");var span=document.createElement("span");var legendCircle=document.createElement("span");legendCircle.classList.add("legend-circle");legendCircle.style.backgroundColor=chartItem.color;li.classList.add("flex","gap-4");li.dataset.channel=itemId+chartItem.label.toLowerCase();span.textContent=chartItem.label;li.appendChild(legendCircle);li.appendChild(span);document.getElementById(itemId+"-legend").appendChild(li);// percentage in chart
var pct=document.createElementNS("http://www.w3.org/2000/svg","text");pct.dataset.channel=itemId+chartItem.label.toLowerCase();pct.setAttribute("x",textX+cx-3.5);pct.setAttribute("font-size",4);pct.setAttribute("font-weight",600);pct.textContent=round(chartItem.value,0)+"%";if(chartItem.value>=4){pct.setAttribute("y",textY+cy+1);pct.setAttribute("fill","#FFF")}else{pct.setAttribute("y",textY+cy-11);if(type=="pie"){pct.setAttribute("y",textY+cy-18)}pct.setAttribute("fill","#3C3E3E")}svg.appendChild(pct);filled+=chartItem.value;// keeps track of how much (%) has been filled, so for the next item we know where should it start
});// link elements by data channel value 
var dataChannel=document.querySelectorAll("[data-channel]");dataChannel.forEach(function(item){item.addEventListener("mouseover",function(){var rel=document.querySelectorAll("[data-channel=\""+item.dataset.channel+"\"]");rel.forEach(function(relItem){relItem.classList.add("is-active");var parentUl=relItem.closest("ul");if(parentUl){parentUl.classList.add("is-active")}})});item.addEventListener("mouseout",function(){var rel=document.querySelectorAll("[data-channel=\""+item.dataset.channel+"\"]");rel.forEach(function(relItem){relItem.classList.remove("is-active");var parentUl=relItem.closest("ul");if(parentUl){parentUl.classList.remove("is-active")}})})})}/**
   * Round number to closest decimal
   */function round(value,decimals){return Number(Math.round(value+"e"+decimals)+"e-"+decimals)}/**
   * Removes %, rounds number to closest decimal and re-attaches the % symbol
   */function roundPercent(value){return round(value.replace("%",""),0)+"%"}/**
   * Gets the index of the item that contains the name of a given country as a value
   */function getIndexFromCountryName(countryName,element){for(var index=0;index<element.length;index++){var option=element[index];if(option.value==countryName){return index}}}})();
